name: wireguard_flutter_plus
description: A Flutter plugin for WireGuard VPN implementation on Android, iOS, macOS, Windows, and Linux. Supports key generation and tunnel management.
version: 1.0.5
homepage: https://orbaninfotech.com
repository: https://github.com/aakashch0179/wireguard_flutter_plus
false_secrets:
  - /example/ios/Runner/GoogleService-Info.plist

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.13.7'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.5
  plugin_platform_interface: ^2.1.8
  process_run: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: orban.group.wireguard_flutter
        pluginClass: WireguardFlutterPlugin
      ios:
        pluginClass: WireguardFlutterPlugin
        sharedDarwinSource: true
      macos:
        pluginClass: WireguardFlutterPlugin
        sharedDarwinSource: true
      windows:
        pluginClass: WireguardFlutterPluginCApi
      linux:
        dartPluginClass: WireGuardFlutter
